<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{d83b5889-783a-434a-87bd-f33de96679bb}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
	PRG_SortingConveyor_proceduralApproach();
	PRG_OOPApproach();
	







]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>